name = "cerebrex-registry"
main = "src/index.ts"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "cerebrex-registry"
database_id = "ee2cdb5a-a3c7-4973-b03f-6a27ed009d88"

[[kv_namespaces]]
binding = "TARBALLS"
id = "6a3a463616354616ac910d40235a9b95"

[[kv_namespaces]]
binding = "RATE_LIMITS"
id = "6bd3fa7800f3448695d23f2d782f6186"

[vars]
ENVIRONMENT = "production"
