/**
 * CerebreX FORGE — MCP Server Code Generator
 * Takes a ParsedSpec and produces a complete, deployable
 * Cloudflare Workers MCP server with Zod validation.
 */

import type { ParsedSpec, ForgeConfig, ForgeResult } from '@cerebrex/types';
import path from 'path';
import fs from 'fs';

export class ForgeEngine {
  private config: ForgeConfig;

  constructor(config: ForgeConfig) {
    this.config = config;
  }

  async generate(): Promise<ForgeResult> {
    const { spec, outputDir, serverName, transport, authScheme } = this.config;

    // Create output directory
    fs.mkdirSync(outputDir, { recursive: true });
    fs.mkdirSync(path.join(outputDir, 'src'), { recursive: true });

    // Generate all files
    await Promise.all([
      this.writeServerFile(),
      this.writeWranglerConfig(),
      this.writePackageJson(),
      this.writeTsConfig(),
      this.writeEnvExample(),
      this.writeReadme(),
    ]);

    return {
      serverName: serverName || spec.title,
      toolCount: spec.endpoints.length,
      transport,
      outputDir,
      files: this.getGeneratedFiles(),
    };
  }

  private async writeServerFile(): Promise<void> {
    const { spec, serverName, transport } = this.config;
    const tools = spec.endpoints.map((e) => this.generateTool(e));

    const serverCode = `/**
 * ${serverName || spec.title} — MCP Server
 * Generated by CerebreX FORGE v0.1.0
 * https://cerebrex.dev
 * 
 * ⚠️  DO NOT commit secrets or API keys to this file.
 *    Use Cloudflare Worker secrets: bunx wrangler secret put SECRET_NAME
 */

import { McpAgent } from 'agents/mcp';
import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { z } from 'zod';

// ── Types ──────────────────────────────────────────────────────────────────────
interface Env {
  // Add your secret bindings here
  // API_KEY: string;
}

// ── MCP Server ─────────────────────────────────────────────────────────────────
export class ${this.toPascalCase(serverName || spec.title)}Server extends McpAgent<Env, unknown, {}> {
  server = new McpServer({
    name: '${serverName || spec.title}',
    version: '${spec.version || '1.0.0'}',
  });

  async init() {
    // Base URL for this API
    const BASE_URL = '${spec.baseUrl || 'https://api.example.com'}';

    // ── Tool Helper ────────────────────────────────────────────────────────────
    const apiCall = async (
      method: string,
      path: string,
      params?: Record<string, unknown>,
      body?: unknown
    ) => {
      const url = new URL(BASE_URL + path);
      
      if (params && method === 'GET') {
        Object.entries(params).forEach(([k, v]) => {
          if (v !== undefined && v !== null) {
            url.searchParams.set(k, String(v));
          }
        });
      }

      const res = await fetch(url.toString(), {
        method,
        headers: {
          'Content-Type': 'application/json',
          'User-Agent': 'CerebreX-MCP/0.1.0',
          // 'Authorization': \`Bearer \${this.env.API_KEY}\`,
        },
        ...(body && method !== 'GET' ? { body: JSON.stringify(body) } : {}),
      });

      if (!res.ok) {
        // Never expose internal error details to the MCP caller
        throw new Error(\`API error: \${res.status}\`);
      }

      return res.json();
    };

${tools.join('\n\n')}
  }
}

// ── Cloudflare Worker Export ───────────────────────────────────────────────────
export default ${this.toPascalCase(serverName || spec.title)}Server.mount('/');
`;

    fs.writeFileSync(path.join(this.config.outputDir, 'src', 'server.ts'), serverCode);
  }

  private generateTool(endpoint: any): string {
    const schemaFields = this.generateZodSchema(endpoint);
    const hasBody = ['POST', 'PUT', 'PATCH'].includes(endpoint.method);
    const pathParams = (endpoint.path.match(/\{(\w+)\}/g) || []).map((p: string) =>
      p.replace(/[{}]/g, '')
    );

    return `    // ── ${endpoint.toolName} ──────────────────────────────────────────────────
    this.server.tool(
      '${endpoint.toolName}',
      ${JSON.stringify(endpoint.description)},
      {
${schemaFields}
      },
      async (params) => {
        const resolvedPath = '${endpoint.path}'${pathParams.map((p: string) => `\n          .replace('{${p}}', String(params.${p}))`).join('')};
        ${hasBody ? `const { ${pathParams.join(', ')}${pathParams.length > 0 ? ', ' : ''}...body } = params;` : ''}
        const data = await apiCall(
          '${endpoint.method}',
          resolvedPath,
          ${!hasBody ? 'params' : 'undefined'},
          ${hasBody ? 'body' : 'undefined'}
        );
        return {
          content: [{ type: 'text', text: JSON.stringify(data, null, 2) }],
        };
      }
    );`;
  }

  private generateZodSchema(endpoint: any): string {
    const fields: string[] = [];

    (endpoint.parameters || []).forEach((param: any) => {
      const zodType = this.schemaToZod(param.schema || { type: 'string' });
      const isRequired = param.required === true;
      const field = isRequired ? zodType : `${zodType}.optional()`;
      const description = param.description ? `.describe(${JSON.stringify(param.description)})` : '';
      fields.push(`        ${param.name}: ${field}${description},`);
    });

    if (!fields.length) {
      fields.push(`        // No parameters required`);
    }

    return fields.join('\n');
  }

  private schemaToZod(schema: any): string {
    if (!schema) return 'z.unknown()';
    switch (schema.type) {
      case 'string':
        return schema.enum ? `z.enum([${schema.enum.map((e: string) => JSON.stringify(e)).join(', ')}])` : 'z.string()';
      case 'integer':
      case 'number':
        return 'z.number()';
      case 'boolean':
        return 'z.boolean()';
      case 'array':
        return `z.array(${this.schemaToZod(schema.items || {})})`;
      case 'object':
        return 'z.record(z.unknown())';
      default:
        return 'z.unknown()';
    }
  }

  private async writeWranglerConfig(): Promise<void> {
    const name = (this.config.serverName || this.config.spec.title)
      .toLowerCase()
      .replace(/[^a-z0-9-]/g, '-');

    const config = `name = "${name}-mcp"
main = "src/server.ts"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

# Add secrets with: bunx wrangler secret put SECRET_NAME
# NEVER put actual secrets here — use wrangler secret put

[env.production]
name = "${name}-mcp-production"
`;
    fs.writeFileSync(path.join(this.config.outputDir, 'wrangler.toml'), config);
  }

  private async writePackageJson(): Promise<void> {
    const pkg = {
      name: (this.config.serverName || this.config.spec.title).toLowerCase().replace(/\s+/g, '-') + '-mcp',
      version: '0.1.0',
      description: `MCP server for ${this.config.serverName || this.config.spec.title} — generated by CerebreX FORGE`,
      scripts: {
        dev: 'wrangler dev',
        deploy: 'wrangler deploy',
        'deploy:prod': 'wrangler deploy --env production',
      },
      dependencies: {
        '@modelcontextprotocol/sdk': '^1.0.0',
        'agents': '^0.0.1',
        'zod': '^3.22.0',
      },
      devDependencies: {
        '@cloudflare/workers-types': '^4.0.0',
        'typescript': '^5.4.0',
        'wrangler': '^3.0.0',
      },
      private: true,
    };
    fs.writeFileSync(path.join(this.config.outputDir, 'package.json'), JSON.stringify(pkg, null, 2));
  }

  private async writeTsConfig(): Promise<void> {
    const tsconfig = {
      compilerOptions: {
        target: 'ES2022',
        module: 'ESNext',
        moduleResolution: 'bundler',
        strict: true,
        lib: ['ES2022'],
        types: ['@cloudflare/workers-types'],
      },
      include: ['src'],
    };
    fs.writeFileSync(path.join(this.config.outputDir, 'tsconfig.json'), JSON.stringify(tsconfig, null, 2));
  }

  private async writeEnvExample(): Promise<void> {
    const envExample = `# Copy this to .dev.vars for local development
# NEVER commit .dev.vars or any file with real secrets

# API_KEY=your-api-key-here
`;
    fs.writeFileSync(path.join(this.config.outputDir, '.dev.vars.example'), envExample);
    // Create .gitignore for the generated server
    fs.writeFileSync(path.join(this.config.outputDir, '.gitignore'), '.dev.vars\n.wrangler/\nnode_modules/\n');
  }

  private async writeReadme(): Promise<void> {
    const name = this.config.serverName || this.config.spec.title;
    const readme = `# ${name} MCP Server

Generated by [CerebreX FORGE](https://cerebrex.dev) v0.1.0.

## Setup

\`\`\`bash
bun install
\`\`\`

## Local Development

\`\`\`bash
cp .dev.vars.example .dev.vars
# Edit .dev.vars with your credentials
bun run dev
\`\`\`

## Deploy to Cloudflare

\`\`\`bash
# Set secrets first
bunx wrangler secret put API_KEY

# Deploy
bun run deploy
\`\`\`

## Tools (${this.config.spec.endpoints.length})

${this.config.spec.endpoints.map((e: any) => `- \`${e.toolName}\` — ${e.description}`).join('\n')}

---
*Generated by [CerebreX](https://cerebrex.dev) — A Real Cool Co.*
`;
    fs.writeFileSync(path.join(this.config.outputDir, 'README.md'), readme);
  }

  private getGeneratedFiles(): string[] {
    return ['src/server.ts', 'wrangler.toml', 'package.json', 'tsconfig.json', '.dev.vars.example', '.gitignore', 'README.md'];
  }

  private toPascalCase(str: string): string {
    return str
      .replace(/[^a-zA-Z0-9]/g, ' ')
      .split(' ')
      .filter(Boolean)
      .map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
      .join('');
  }
}
